from llm_sdk import Small_LLM_Model
from .models import FunctionsDefinitions, FunctionsPrompt
import numpy as np
from typing import Any


class Llm:
    """Wrapper around the LLM that generates function calls.

    Every answer is produced token by token with constrained decoding:
    the logits of the tokens that would break the expected format are
    set to -inf before choosing the next token.

    Attributes:
        llm: The Small_LLM_Model used to encode, decode and get logits.
        vocab: Mapping from the decoded text of a token to its id.
        end_token: Id of the <|im_end|> token, used to stop a generation.
        max_token: Maximum number of tokens of a generation, set by
            get_max_token().
    """

    def __init__(self, prompts: list[FunctionsPrompt],
                 functions: list[FunctionsDefinitions]) -> None:
        """Load the model and build the vocabulary."""
        self.llm = Small_LLM_Model()
        self.vocab: dict[str, int] = {}
        self.load_vocab()
        self.end_token = 151645
        self.get_max_token(prompts, functions)

    def load_vocab(self) -> None:
        """Build the text -> id mapping of the whole vocabulary.

        Every token id is decoded once, so that the generation loops can
        find the tokens matching a text without calling encode or decode.
        """
        vocab_size = len(self.llm.get_logits_from_input_ids([0]))
        for token_id in range(vocab_size):
            text = self.llm.decode([token_id])
            if text != "":
                self.vocab[text] = token_id

    def get_max_token(self, prompts: list[FunctionsPrompt],
                      functions: list[FunctionsDefinitions]) -> None:
        """Set max_token between the longest function name and the
        longest prompt.

        Args:
            prompts: The available prompts.
            functions: The available functions.
        """
        p_length = max([len(p.prompt) for p in prompts], default=0)
        f_length = max(len(f.name) for f in functions)
        if p_length > f_length:
            self.max_token = p_length * 2
        else:
            self.max_token = f_length * 2

    def find_the_function(self,
                          prompt: str,
                          functions: list[FunctionsDefinitions]
                          ) -> FunctionsDefinitions:
        """Choose the function matching the user's prompt with the LLM.

        Args:
            prompt: The natural language request of the user.
            functions: The available functions.

        Returns:
            The function whose name was generated by the model.

        Raises:
            Exception: If the generated name matches no function.
        """
        prompt_text = (
         "<|im_start|>system\n"
         "Return a function name corresponding to the user's prompt\n"
         f"Functions: {functions}\n"
         "<|im_end|>\n"
         "<|im_start|>user\n"
         f"Description: \"{prompt}\"\n"
         "<|im_end|>\n"
         "<|im_start|>assistant\n"
         "<think>\n\n</think>\n\n"
        )
        sentence = self.llm.encode(prompt_text)[0].tolist()
        answer = self.answer_building(sentence, [f.name for f in functions])
        for function in functions:
            if function.name == answer:
                return function
        raise Exception(f"[ERROR]: unknown function {answer}")

    def find_valid_tokens(self, answer: str, names: list[str]) -> list[int]:
        """Get the tokens that keep `answer` a prefix of at least one name.

        The end token is also allowed when `answer` is already a complete
        name.

        Args:
            answer: The text generated so far.
            names: The possible final answers.

        Returns:
            The ids of the allowed tokens.
        """
        authorized: list[int] = []
        for name in names:
            if not name.startswith(answer):
                continue
            rest = name[len(answer):]
            if not rest:
                authorized.append(self.end_token)
            for i in range(1, len(rest) + 1):
                if rest[:i] in self.vocab:
                    authorized.append(self.vocab[rest[:i]])
        return authorized

    def answer_building(self, sentence: list[int], names: list[str]) -> str:
        """Generate one of the given names, token by token.

        Args:
            sentence: The token ids of the context. The generated tokens
                are appended to it.
            names: The possible answers.

        Returns:
            The generated name, which is always one of `names`.

        Raises:
            Exception: If no token can follow the current text, or if the
                generation exceeds max_token tokens.
        """
        answer = ""
        token = 0
        while token <= self.max_token:
            authorized = self.find_valid_tokens(answer, names)
            if not authorized:
                raise Exception("[ERROR]: No tokens available to follow")
            next_token = self.generate_next_token(sentence, authorized)
            if next_token == self.end_token:
                return answer
            sentence.append(next_token)
            answer += self.llm.decode([next_token])
            token += 1
        raise Exception(f"[ERROR]: limit of {self.max_token} tokens raised")

    def generate_next_token(self,
                            sentence: list[int],
                            authorized: list[int]) -> int:
        """Choose the most likely token among the authorized ones.

        Args:
            sentence: The token ids of the context.
            authorized: The ids of the tokens the model may choose.

        Returns:
            The id of the chosen token.
        """
        logits = np.array(self.llm.get_logits_from_input_ids(sentence))
        mask = np.full(len(logits), -np.inf)
        mask[authorized] = 0
        return int(np.argmax(logits + mask))

    def add_text_to_answer(self, sentence: list[int], text: str) -> None:
        """Append the tokens of a text to the context without the model.

        Used to write the fixed parts of the JSON (braces, keys, quotes).

        Args:
            sentence: The token ids of the context, modified in place.
            text: The text to add.
        """
        sentence.extend(self.llm.encode(text)[0].tolist())

    def find_parameters(self,
                        prompt: str,
                        function: FunctionsDefinitions) -> dict[str, Any]:
        """Generate the value of each parameter of a function.

        The JSON structure is written by the program and the model only
        generates the values, with a constraint depending on their type.

        Args:
            prompt: The natural language request of the user.
            function: The function chosen for this prompt.

        Returns:
            The parameter names mapped to their values, converted to the
            Python type matching their schema type.
        """
        example: dict[str, str] = {}
        for name, kind in function.parameters.items():
            example[name] = kind.type
        prompt_text = (
             "<|im_start|>system\n"
             "Extract parameters valus from a prompt for the given function\n"
             f"function: {function.description}\n"
             f"Answer must following this parsing: {example}\n"
             "Example: \"Replace all spaces in 'a b c' with underscores\" "
             "-> {\"text\": \"a b c\", \"regex\": \"\\\\s\", "
             "\"replacement\": \"_\"}\n"
             "<|im_end|>\n"
             "<|im_start|>user\n"
             f"Prompt: \"{prompt}\"\n"
             "<|im_end|>\n"
             "<|im_start|>assistant\n"
             "<think>\n\n</think>\n\n"
            )
        sentence = self.llm.encode(prompt_text)[0].tolist()
        result: dict[str, Any] = {}
        separator = "{"
        for name, kind in function.parameters.items():
            key = f'{separator}"{name}":'
            separator = ", "
            if kind.type == "integer":
                self.add_text_to_answer(sentence, key)
                result[name] = int(self.generate_number(sentence, True))
            elif kind.type == "boolean":
                self.add_text_to_answer(sentence, key + " ")
                answer = self.answer_building(sentence, ["true", "false"])
                if answer == "true":
                    result[name] = True
                else:
                    result[name] = False
            elif kind.type == "string":
                self.add_text_to_answer(sentence, key + ' "')
                result[name] = self.generate_str(sentence)
            else:
                self.add_text_to_answer(sentence, key)
                result[name] = float(self.generate_number(sentence, False))
        return result

    def generate_number(self, sentence: list[int], is_integer: bool) -> str:
        """Generate a number token by token.

        Only a leading space or space and minus sign, digits and a single
        decimal point are allowed. The generation stops on "," or "}",
        which are only allowed right after a digit.

        Args:
            sentence: The token ids of the context. The generated tokens
                are appended to it.
            integer: True to forbid the decimal point.

        Returns:
            The generated number as text.

        Raises:
            Exception: If the number exceeds max_token tokens.
        """
        digits = [self.vocab[c] for c in "0123456789"]
        allowed: list[int] = []
        answer = ""
        for i in range(self.max_token):
            if i == 0:
                allowed = [self.vocab[" "], self.vocab[" -"]]
            elif not is_integer:
                allowed = digits + [self.vocab["."]]
            else:
                allowed = digits[:]
            if sentence[-1] in digits:
                allowed.extend([self.vocab[","], self.vocab["}"]])
            next_token = self.generate_next_token(sentence, allowed)
            if next_token == self.vocab["."]:
                is_integer = True
            if next_token in [self.vocab[","], self.vocab["}"]]:
                return answer
            sentence.append(next_token)
            answer += self.llm.decode([next_token])
        raise Exception("[ERROR]: number too long")

    def generate_str(self, sentence: list[int]) -> str:
        """Generate a string value token by token.
        The generation stops at the first double quote, which is then
        written in the context to close the string.
        Args:
            sentence: The token ids of the context. The generated tokens
                are appended to it.
        Returns:
            The generated text, without the closing quote.
        Raises:
            Exception: If the string exceeds max_token tokens.
        """
        answer = ""
        for _ in range(self.max_token):
            logits = self.llm.get_logits_from_input_ids(sentence)
            next_token = int(np.argmax(logits))
            text = self.llm.decode([next_token])
            if '"' in text:
                answer += text[:text.index('"')]
                self.add_text_to_answer(sentence, '"')
                return answer
            sentence.append(next_token)
            answer += text
        raise Exception("[ERROR]: The sentence is too long")
